### ISSUE TITLE
How can we perform case analysis on envelopes?

### ISSUE THREAD

**Issue by jonathanknowles** [cdepillabout/servant-checked-exceptions#28] opened 2019-02-13 01:56 UTC
I'm seeing unusual behaviour with the following piece of client code:
```Haskell
getLocationById   
  :: Integer  
  -> ClientM (Envelope '[InvalidLocationError, NoSuchLocationError] Location) 
getLocationById = client api  
  
main :: IO () 
main = do 
  manager <- newManager defaultManagerSettings
  let env = mkClientEnv manager baseUrl   
  print =<< runClientM program env
  
program :: ClientM () 
program = do  
  liftIO $ putStrLn "Enter the ID of a location (non-negative integer):"  
  locationId <- liftIO readLn 
  result <- getLocationById locationId
  liftIO $ do 
    putStrLn "Result:"
    putStrLn $ catchesEnvelope (show, show) show result
```
A **successful** lookup with the program produces the following output:
```
Enter the ID of a location (non-negative integer):
0
Result:
Location {locationId = 0, locationName = "Amsterdam"}
Right ()
```
But an **unsuccessful** lookup produces the following output:
```
Enter the ID of a location (non-negative integer):
-1
Left (FailureResponse (Response {responseStatusCode = Status {statusCode = 400, statusMessage = "Bad Request"}, responseHeaders = fromList [("Transfer-Encoding","chunked"),("Date","Wed, 13 Feb 2019 01:47:56 GMT"),("Server","Warp/3.2.26"),("Content-Type","application/json;charset=utf-8")], responseHttpVersion = HTTP/1.1, responseBody = "{\"err\":[]}"}))
```

In the event that calling `getLocationById` results in an exception (either `InvalidLocationError` or `NoSuchLocationError`), I would expect the case analysis of `catchesEnvelope` to kick in. However, what actually happens is that `putStrLn "Result"` is never executed.

It seems `servant-client` returns a `Left (FailureResponse ..)` in the case of `statusCode == 400` or `statusCode == 404`, causing the above function to short-circuit, meaning that we're unable to perform case analysis.

Is this behaviour intentional? If not, is there a known workaround?

(**original source**: https://github.com/jonathanknowles/servant-checked-exceptions-example)

**Comment by cdepillabout** [comment] 2019-02-13 02:47
I think this is caused by the same reason as #27.

When I looked into it a couple months ago, this was caused by `servant-client` swallowing up all non-2XX HTTP responses.  In #27, I linked to a modified version of `servant-client` that does not swallow up non-2XX HTTP response (but of course this is not officially supported).

If you want to use `servant-checked-exceptions` with `servant-client`, you can't return non-2XX HTTP responses from your server.

Since this has bitten at least two people now, it would be good to add it to the `servant-checked-exceptions` README as a known bug.  Would you be able to send a PR for this?

Also, if you wanted to create an issue on the Servant repo about this, I'd do whatever is necessary to provide support in `servant-checked-exceptions` after it is fixed in Servant.

--------------------------------------------------

I'll go ahead and close this since is it a duplicate of #27, but feel free to continue the conversation on #27 if you have any additional questions.

**Closed as completed** 2019-02-13 02:48 UTC

**Comment by jonathanknowles** [comment] 2019-02-15 02:20
@cdepillabout Many thanks for your response. You're right that it's a duplicate of #27.

I'll add any further comments to #27.
